### ISSUE TITLE
Add Coverage Info for .Net Tests

### ISSUE THREAD

**Issue by FelixS90** [ZEISS/imgdoc2#22]
**Is your feature request related to a problem? Please describe.**
So far we have only been collecting coverage information for the C++ part implemented as part of #4 . This should be complemented by information on .Net coverage to have more complete picture.

**Describe the solution you'd like**
Extend the [dotnet test](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test) command by `--collect:"XPlat Code Coverage"` and upload the resulting [coverage.cobertura.xml](https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-code-coverage?tabs=windows) file to codecov.

This should be added as a component :
```yaml
- component_id: "id_imgdoc2net"
      name: imgdoc2net
      paths:
        - "dotnet/imgdoc2Net/"
``` 
in https://github.com/ZEISS/imgdoc2/blob/main/.github/codecov.yml.

**Describe alternatives you've considered**
None.
